name: Store form submit as JSON
on:
  repository_dispatch:
    types: [form_submit]
permissions:
  contents: write
jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save payload to data/submissions/*.json
        run: |
          mkdir -p data/submissions
          python - <<'PY'
          import os, json, time, uuid, pathlib
          ev = json.load(open(os.environ['GITHUB_EVENT_PATH']))
          payload = ev.get('client_payload', {})
          payload.setdefault('submitted_at', time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()))
          fname = time.strftime('%Y%m%dT%H%M%SZ', time.gmtime()) + "_" + uuid.uuid4().hex[:6] + ".json"
          out = pathlib.Path("data/submissions")/fname
          out.write_text(json.dumps(payload, ensure_ascii=False, indent=2))
          PY
      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/submissions
          git commit -m "form: store JSON submission" || echo "No changes"
          git push
